# Generated by Django 4.1.3 on 2022-12-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("DepartmentId", models.AutoField(primary_key=True, serialize=False)),
                ("DepartmentName", models.CharField(max_length=499)),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("EmployeeId", models.AutoField(primary_key=True, serialize=False)),
                ("EmployeetName", models.CharField(max_length=499)),
                ("Department", models.CharField(max_length=499)),
                ("DateofJoining", models.DateField()),
                ("PhotoFileName", models.CharField(max_length=499)),
            ],
        ),
    ]
